### PR TITLE
Implements transaction from current payment request if it's expanded

### PR DESCRIPTION
**Pull request by shahriar-vdc**
- Adds expands to build request endpoint
- Adds resources for Transaction in Payment response if it's expanded

### CODE REVIEW

**Comment by aait** [comment]
@shahriar-vdc There are missing tests

**Comment by asbjornu** [comment]
@shahriar-vdc, there's [one failing unit test](https://github.com/SwedbankPay/swedbank-pay-sdk-php/pull/49/checks?check_run_id=2067522462#step:17:126):

```
There was 1 error:

1) InvoicePaymentTest::testCapture
SwedbankPay\Api\Client\Exception: 
>>>>>>>> BEGIN PAYEX API CLIENT REQUEST DEBUG INFO >>>>>>>>

Request Method: POST
Request URL: https://api.externalintegration.payex.com/psp/invoice/payments/e775ae17-55da-4332-7436-08d8cf42e7a6/captures
Request Headers: Accept: application/json
Session-Id: cbf7784b-96fa-4967-8fdd-fc76323efde7
Forwarded: for=127.0.0.1; proto=https
Authorization:  ***
Content-Type: application/json; charset=utf-8
Content-Length: 546
Request Body:
{
    "transaction": {
        "activity": "FinancingConsumer",
        "amount": 1,
        "description": "Test Capture",
        "itemDescriptions": [
            {
                "amount": 1,
                "description": "item description 1"
            }
        ],
        "payeeReference": "fdb71903a241",
        "receiptReference": "195fa2bf22a0",
        "vatAmount": 0,
        "vatSummary": [
            {
                "amount": 1,
                "vatAmount": 0,
                "vatPercent": 0
            }
        ]
    }
}

Response Code: 403
Response Body:
{"sessionId":"cbf7784b-96fa-4967-8fdd-fc76323efde7","type":"https://api.payex.com/psp/errordetail/forbidden","title":"Operation not allowed","status":403,"instance":"http://api.externalintegration.payex.com/psp/invoice/payments/e775ae17-55da-4332-7436-08d8cf42e7a6/captures","detail":"Not allowed, description in problems node!","problems":[{"name":"RejectedByThirdParty","description":"Capture cannot be performed due to exceeded authorization-time. Response code 1248 - Process online request: Method [CaptureInvoice] ProcessId [25795651] Status[received] Message [Matched externalReservationId [41100214561] cannot be used because it is not open, current status is [Closed]]"}]}
```

**Comment by asbjornu** [comment]
> These aren't actually unit tests, but rather integration tests.

Correct. Either way, they need to work.

> And it's failing because the payment has already been captured.

Can we remedy this, somehow?

**Comment by shahriar-vdc** [comment]
Yes, I think these types of methods will not work at all as they are relying on hardcoded `$paymentId`. So, instead of hardcoding the ID, we can use the payment ID that we receive while creating a new payment. The tests will fail wherever we are using hard-coded payment IDs.

So instead of setting `$this->paymentId` here, we can use `$paymentId` here & in similar places https://github.com/SwedbankPay/swedbank-pay-sdk-php/blob/master/tests/InvoicePaymentTest.php#L278

**Review by asbjornu — APPROVED** [review]

**Pull request merged**
