### PR TITLE
WOO-66: System User Agent Fixes

### PR DESCRIPTION
**Pull request by olegisk**

### CODE REVIEW

**Review by trieutran91 — COMMENTED** [review]
Misspelling @deprecated and indent fixes will do it here 😃

**Review by asbjornu — CHANGES_REQUESTED** [review]
I see that I have not explained this thoroughly enough. `User-Agent` should be added as an HTTP header, not as `initiatingSystemUserAgent` in the request. [This is described in more detail on the developer portal](https://developer.stage.swedbankpay.com/introduction#user-agent).

**Review by aait — APPROVED** [review]

**Comment by aait** [comment]
> I see that I have not explained this thoroughly enough. `User-Agent` should be added as an HTTP header, not as `initiatingSystemUserAgent` in the request. [This is described in more detail on the developer portal](https://developer.stage.swedbankpay.com/introduction#user-agent).

Fixed

**Review by trieutran91 — APPROVED** [review]
👍

**Pull request merged**
